###################################################################

# Created by write_sdc on Tue Oct 28 15:59:39 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {DOUT3k[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k1[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT3k2[0]}]
set_load -pin_load 3.40189 [get_ports VOUT]
create_clock [get_ports clk]  -name MY_CLK  -period 7.3  -waveform {0 3.65}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3k2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C3[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C4[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C5[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C6[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C7[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C8[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C9[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {C10[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RSTn]
